# Generated by Django 5.0.6 on 2025-09-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(db_index=True, max_length=5, unique=True)),
                ('employee_name', models.CharField(max_length=100)),
                ('employees_position', models.CharField(max_length=100)),
            ],
        ),
    ]
